var s_iScaleFactor=1,s_bIsIphone=!1,s_oCanvasLeft,s_oCanvasTop,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function getSize(a){var b=a.toLowerCase(),c=window.document,e=c.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var f=c.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var d=c.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+b+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";f.appendChild(d);e.insertBefore(f,c.head);
a=7==d["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(f)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var b=getSize("Width");_checkOrientation(b,a);var c=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),e=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c;if(c<a){var f=a-c;c+=f;e+=CANVAS_WIDTH/CANVAS_HEIGHT*f}else e<b&&(f=b-e,e+=f,c+=CANVAS_HEIGHT/CANVAS_WIDTH*f);f=a/2-c/2;var d=b/2-e/2,h=CANVAS_WIDTH/e;if(d*h<-EDGEBOARD_X||f*h<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),b/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,f=(a-c)/2,d=(b-e)/2,h=CANVAS_WIDTH/e;s_iOffsetX=-1*d*h;s_iOffsetY=-1*f*h;0<=f&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*e,s_oStage.canvas.height=2*c,canvas.style.width=e+"px",canvas.style.height=c+"px",s_oStage.scaleX=
s_oStage.scaleY=2*Math.min(e/CANVAS_WIDTH,c/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",e+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=e,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(e/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",d+"px")}}
function _checkOrientation(a,b){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>b?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,b,c){var e=new createjs.Bitmap(a),f=new createjs.Shape;b&&c?f.graphics.beginFill("#fff").drawRect(0,0,b,c):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=f;return e}function createSprite(a,b,c,e,f,d){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-c,-e,f,d);a.hitArea=b;return a}
function randomFloatBetween(a,b,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(c))}function shuffle(a){for(var b=a.length,c,e;0!==b;)e=Math.floor(Math.random()*b),--b,c=a[b],a[b]=a[e],a[e]=c;return a}function bubbleSort(a){do{var b=!1;for(var c=0;c<a.length-1;c++)a[c]>a[c+1]&&(b=a[c],a[c]=a[c+1],a[c+1]=b,b=!0)}while(b)}function compare(a,b){return a.index>b.index?-1:a.index<b.index?1:0}
function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=Math.floor(a-60*b);var c="",c=10>b?c+("0"+b+":"):c+(b+":");return 10>a?c+("0"+a):c+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var b=a.length,c,e;0<b;)e=Math.floor(Math.random()*b),b--,c=a[b],a[b]=a[e],a[e]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[b]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var b="hidden";b in document?document.addEventListener("visibilitychange",a):(b="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(b="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(b="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,b,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(b),s_aSounds[a].loop(c),s_aSounds[a]):null}
function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(b)}function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(b)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var e=b[c].split("=");if(e[0]==a)return e[1]}}
function CSpriteLibrary(){var a,b,c,e,f,d;this.init=function(h,l,g){c=b=0;e=h;f=l;d=g;a={}};this.addSprite=function(c,e){a.hasOwnProperty(c)||(a[c]={szPath:e,oSprite:new Image},b++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(d)};this._onSpriteLoaded=function(){e.call(d);++c===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return b}}var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=220,EDGEBOARD_Y=220,DISABLE_SOUND_MOBILE=!1,FONT_GAME="walibi0615bold",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,CARD_WIDTH=160,CARD_HEIGHT=252,MAX_CARDS=50,SCORE_MATCH_CARD,SCORE_TIME_LEFT_MULT,TIME_FOR_MATCH_MULT,NUM_BACKGROUNDS=4,TIME_SHOW_CARDS,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
TEXT_GAMEOVER="GAME OVER";TEXT_PLAY="PLAY";TEXT_LEVEL_SCORE="LEVEL SCORE";TEXT_LEVELCOMPLETED="STAGE CLEARED!";TEXT_TIMELEFT="Time ";TEXT_SCORE="Score ";TEXT_MATCH_SCORE="SCORE MATCHING";TEXT_TIMEBONUS="TIME BONUS";TEXT_TOTALSCORE="TOTAL SCORE";TEXT_VICTORY="CONGRATULATIONS!!";TEXT_PLAY_AGAIN="PLAY AGAIN";TEXT_DEVELOPED="DEVELOPED BY";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,b,c,e,f,d,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(l);e.x=CANVAS_WIDTH/2-l.width/2;e.y=CANVAS_HEIGHT-210;h.addChild(e);a=l.width;b=l.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,b);h.addChild(f);e.mask=
f;c=new createjs.Text("","30px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-210;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";h.addChild(c);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;h.addChild(d)};this.refreshLoader=function(d){c.text=d+"%";f.graphics.clear();d=Math.floor(d*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,d,b)};this._init()}
function CMain(a){var b,c=0,e=0,f=STATE_LOADING,d,h;this.initContainer=function(){s_oStage=new createjs.Stage("canvas");createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;d=new CPreloader;b=!0};this.soundLoaded=function(){c++;
d.refreshLoader(Math.floor(c/e*100));c===e&&(d.unload(),this.gotoMenu())};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"card",loop:!1,volume:1,ingamename:"card"});a.push({path:"./sounds/",filename:"next_level",loop:!1,volume:1,ingamename:"next_level"});a.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});a.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});a.push({path:"./sounds/",filename:"right",loop:!1,volume:1,
ingamename:"right"});a.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});e+=a.length;s_aSounds=[];for(var b=0;b<a.length;b++)s_aSounds[a[b].ingamename]=new Howl({src:[a[b].path+a[b].filename+".mp3",a[b].path+a[b].filename+".ogg"],autoplay:!1,preload:!0,loop:a[b].loop,volume:a[b].volume,onload:s_oMain.soundLoaded()})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_menu_bg","./sprites/but_menu_bg.png");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("bg_1","./sprites/bg_1.jpg");s_oSpriteLibrary.addSprite("bg_2","./sprites/bg_2.jpg");s_oSpriteLibrary.addSprite("bg_3","./sprites/bg_3.jpg");s_oSpriteLibrary.addSprite("bg_4","./sprites/bg_4.jpg");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");s_oSpriteLibrary.addSprite("msg_box",
"./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;d.refreshLoader(Math.floor(c/e*100));c===e&&(d.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};
this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();b=!0};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){h=new CGame(l);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=
!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==b){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;var l=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings,s_bFullscreen=!1,s_aSounds;
function CTextButton(a,b,c,e,f,d,h,l){var g,q,r,k=1,n,t,p,v,m,u,w;this._init=function(a,b,c,e,d,k,f,h){g=!1;n=[];t=[];w=h;v=createBitmap(c);q=c.width;r=c.height;h=Math.ceil(f/20);m=new createjs.Text(e,f+"px "+d,"#000000");var l=m.getBounds();m.textAlign="center";m.textBaseline="alphabetic";m.x=c.width/2+h;m.y=Math.floor(c.height/2)+l.height/3+h;u=new createjs.Text(e,f+"px "+d,k);u.textAlign="center";u.textBaseline="alphabetic";u.x=c.width/2;u.y=Math.floor(c.height/2)+l.height/3;p=new createjs.Container;
p.x=a;p.y=b;p.regX=c.width/2;p.regY=c.height/2;p.cursor="pointer";p.addChild(v,m,u);w.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown");p.off("pressup");w.removeChild(p)};this.setVisible=function(a){p.visible=a};this.setScale=function(a){k=p.scaleX=p.scaleY=a};this.enable=function(){g=!1;v.filters=[];v.cache(0,0,q,r)};this.disable=function(){g=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);v.filters=[new createjs.ColorMatrixFilter(a)];v.cache(0,0,q,r)};this._initListener=
function(){oParent=this;p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){n[a]=b;t[a]=c};this.buttonRelease=function(){g||(p.scaleX=k,p.scaleY=k,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(t[ON_MOUSE_UP]))};this.buttonDown=function(){g||(playSound("click",1,!1),p.scaleX=p.scaleY=k-.1*k,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){p.x=a;p.y=b};this.changeText=function(a){u.text=a;m.text=a};this.setX=function(a){p.x=
a};this.setY=function(a){p.y=a};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};this._init(a,b,c,e,f,d,h,l);return this}
function CGfxButton(a,b,c,e){var f,d,h,l,g;this._init=function(a,b,c,e){f=!1;d=1;h=[];l=[];g=createBitmap(c);g.x=a;g.y=b;g.scaleX=g.scaleY=d;g.regX=c.width/2;g.regY=c.height/2;g.cursor="pointer";e.addChild(g);this._initListener()};this.unload=function(){s_bMobile?g.off("mousedown",this.buttonDown):(g.off("mousedown",this.buttonDown),g.off("mouseover",this.buttonOver));g.off("pressup",this.buttonRelease);e.removeChild(g)};this.setVisible=function(a){g.visible=a};this.setClickable=function(a){f=!a};
this._initListener=function(){if(s_bMobile)g.on("mousedown",this.buttonDown);else g.on("mousedown",this.buttonDown),g.on("mouseover",this.buttonOver);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;l[a]=c};this.buttonRelease=function(){f||(g.scaleX=d,g.scaleY=d,h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP]))};this.buttonDown=function(){f||(g.scaleX=.9*d,g.scaleY=.9*d,playSound("click",1,!1),h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};this.buttonOver=
function(a){s_bMobile||f||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(g).to({scaleX:.9*d,scaleY:.9*d},850,createjs.Ease.quadOut).to({scaleX:d,scaleY:d},650,createjs.Ease.quadIn).call(function(){q.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(g).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){q.trebleAnimation()})};this.setPosition=function(a,
b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};var q=this;this._init(a,b,c,e);return this}
function CToggle(a,b,c,e,f){var d,h,l,g;this._init=function(a,b,c,e){h=[];l=[];var f=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});d=e;g=createSprite(f,"state_"+d,c.width/2/2,c.height/2,c.width/2,c.height);g.x=a;g.y=b;g.stop();q.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_bMobile||g.off("mouseover",this.buttonOver);
q.removeChild(g)};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease);if(!s_bMobile)g.on("mouseover",this.buttonOver)};this.addEventListener=function(a,b,c){h[a]=b;l[a]=c};this.setActive=function(a){d=a;g.gotoAndStop("state_"+d)};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;playSound("click",1,0);d=!d;g.gotoAndStop("state_"+d);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP],d)};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;h[ON_MOUSE_DOWN]&&
h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){g.x=a;g.y=b};var q=f;this._init(a,b,c,e)}
function CMenu(){var a,b,c,e,f,d,h,l,g,q,r,k,n,t,p=null,v=null;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);f=CANVAS_WIDTH/2;d=CANVAS_HEIGHT-70;var m=s_oSpriteLibrary.getSprite("but_menu_bg");q=new CTextButton(f,d,m,TEXT_PLAY,FONT_GAME,"White","24",s_oStage);q.setScale(2);q.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);var u=s_oSpriteLibrary.getSprite("but_credits");c=u.width/2+10;e=u.height/2+10;r=new CGfxButton(c,e,u,s_oStage);r.addEventListener(ON_MOUSE_UP,
this._onButCreditsRelease,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(m=s_oSpriteLibrary.getSprite("audio_icon"),h=CANVAS_WIDTH-m.height/2-20,l=m.height/2+20,k=new CToggle(h,l,m,s_bAudioActive,s_oStage),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),a=h-m.width/2-20):a=CANVAS_WIDTH-m.height/2-20;b=m.height/2+20;m=window.document;u=m.documentElement;p=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;v=m.exitFullscreen||m.mozCancelFullScreen||
m.webkitExitFullscreen||m.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(p=!1);p&&!1===inIframe()&&(m=s_oSpriteLibrary.getSprite("but_fullscreen"),t=new CToggle(a,b,m,s_bFullscreen,s_oStage),t.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(n);createjs.Tween.get(n).to({alpha:0},1E3).call(function(){n.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){q.unload();
q=null;r.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;p&&!1===inIframe()&&t.unload();s_oStage.removeAllChildren()};this.refreshButtonPos=function(g,n){q.setPosition(f,d-n);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(h-g,n+l);p&&!1===inIframe()&&t.setPosition(a-g,b+n);r.setPosition(c+g,e+n)};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame();s_oMenu=null};this._onButCreditsRelease=function(){new CCredits};this._onAudioToggle=
function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(v.call(window.document),s_bFullscreen=!1):(p.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var b=!0,c=4,e=0,f=0,d,h,l=0,g,q=0,r=0,k=[],n,t,p,v,m,u;this._init=function(){var a={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card0:[0],card1:[1],card2:[2],card3:[3],card4:[4],card5:[5],card6:[6],card7:[7],card8:[9],card9:[10],card10:[11],card11:[12],card12:[13],card13:[14],card14:[15],card15:[16],back:[17]}};this.spriteSheet=new createjs.SpriteSheet(a);n=new createjs.Container;
s_oStage.addChild(n);u=new createjs.Container;s_oStage.addChild(u);t=new CInterface(formatTime(d));p=new CNextLevel;v=new CGameOver;m=new CVictory;this.nextLevel()};this.unload=function(a){for(var b=0;b<k.length;b++)k[b].unload();s_oStage.removeAllChildren();t.unload();a&&$(s_oMain).trigger("end_level",e);$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",l);s_oMain.gotoMenu()};this.cardClicked=function(a,c){!0===a.isFolded()&&!1===b&&2>f&&a.flipCard()};this.addFlippedCard=function(){f++;
2===f&&!1===b&&this.checkMatching()};this.checkMatching=function(){for(var a=[],d=[],m=0;m<c;m++)!1===k[m].isFolded()&&(d.push(k[m].getType()),a.push(m));if(d[0]===d[1]){if(d=1,h<TIME_FOR_MATCH_MULT?(h=0,t.showMultiplier(g),d=g,g++):(g=2,h=0),playSound("right",1,!1),k[a[0]].eliminateCard(),k[a[1]].eliminateCard(),k.splice(a[0],1),k.splice(a[1]-1,1),c-=2,l+=SCORE_MATCH_CARD*d,q+=SCORE_MATCH_CARD*d,t.refreshScore(l),0===c&&e<=s_aCardsPerLevel.length){b=!0;var n=this;setTimeout(function(){n.checkVictory()},
1E3)}}else k[a[0]].flipCard(),k[a[0]].clickListener(),k[a[1]].flipCard(),k[a[1]].clickListener();f=0};this.checkVictory=function(){b=!0;r=Math.round(d/1E3*SCORE_TIME_LEFT_MULT);l+=r;t.refreshScore(l);$(s_oMain).trigger("end_level",e);e<s_aCardsPerLevel.length?(playSound("next_level",1,!1),p.display(q,r,q+r,l,e)):(playSound("win",1,!1),m.display(l))};this.nextLevel=function(){e++;$(s_oMain).trigger("start_level",e);n.removeAllChildren();var a=createBitmap(s_oSpriteLibrary.getSprite("bg_"+(Math.floor(Math.random()*
NUM_BACKGROUNDS)+1)));n.addChild(a);a=CLevels(e);c=a.cardsNum;d=a.timeAllotted;h=TIME_FOR_MATCH_MULT;for(var f=[],l=0;l<c/2;l++)f[l]=l,f[l+c/2]=l;for(l=0;l<c;l++){var m=Math.floor(Math.random()*f.length);k[l]=new CCard(a.cardsPos[l][0],a.cardsPos[l][1],"card"+f[m],a.cardZoomFactor,u);f.splice(m,1)}_iGameOverScore=r=q=0;g=2;b=!1};this.suspendUpdates=function(){b=!0};this.restartUpdates=function(){0<c&&(b=!1)};this.update=function(){b||(d-=s_iTimeElaps,h+=s_iTimeElaps,0>d?(b=!0,d=0,playSound("game_over",
1,!1),v.display(l),e=1):t.update(formatTime(d)))};this.spriteSheet={};s_oGame=this;SCORE_MATCH_CARD=a.score_match_card;SCORE_TIME_LEFT_MULT=a.score_time_left_mult;TIME_FOR_MATCH_MULT=a.time_match_mult;s_aCardsPerLevel=a.card_per_level;s_aSecsPerLevel=a.time_level;TIME_SHOW_CARDS=1E3*a.show_cards;ENABLE_FULLSCREEN=a.fullscreen;this._init()}var s_aCardsPerLevel,s_aSecsPerLevel,s_oGame;
function CCard(a,b,c,e,f){var d=!1,h,l,g,q,r,k,n,t;this._init=function(a,b,c,e,f){g=a;q=b;_bEliminated=!1;h=!0;l=c;t=f;k=createSprite(s_oGame.spriteSheet,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);k.x=g<CANVAS_WIDTH/2?g-CANVAS_WIDTH:CANVAS_WIDTH+g;k.y=q+Math.floor(0*(Math.random()-.5));r=e;k.scaleX=k.scaleY=r;n=this;k.cursor="pointer";k.on("click",function(){this.clicked()},n);d=!0;s_oGame.suspendUpdates();t.addChild(k);var m=this;createjs.Tween.get(k).to({alpha:1,x:g,y:q},500).call(function(){d=
!1;s_oGame.restartUpdates();0<TIME_SHOW_CARDS&&m.showCardFirstTime()})};this.unload=function(){t.removeChild(k)};this.update=function(){};this.clicked=function(){!1===d&&h&&(s_oGame.cardClicked(this,l),playSound("card",1,!1),this.clickListener())};this.showCardFirstTime=function(){d=!0;createjs.Tween.get(k).to({scaleX:.1},100).call(function(){t.removeChild(k);k=createSprite(s_oGame.spriteSheet,l,CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);k.x=g;k.y=q;k.scaleX=k.scaleY=r;t.addChild(k);createjs.Tween.get(k).wait(TIME_SHOW_CARDS).to({scaleX:r},
100).call(function(){h=d=!1;n.clickListener();n.flipCard()},n)})};this.flipCard=function(){!0===h?(d=!0,createjs.Tween.get(k).to({scaleX:.1},100).call(function(){t.removeChild(k);k=createSprite(s_oGame.spriteSheet,l,CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);k.x=g;k.y=q;k.scaleX=k.scaleY=r;t.addChild(k);createjs.Tween.get(k).to({scaleX:r},100).call(function(){h=d=!1;s_oGame.addFlippedCard();n.clickListener()},n)})):(playSound("card",1,!1),d=!0,createjs.Tween.get(k).to({scaleX:.1},100).call(function(){t.removeChild(k);
k=createSprite(s_oGame.spriteSheet,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);k.x=g;k.y=q;k.scaleX=k.scaleY=r;t.addChild(k);createjs.Tween.get(k).to({scaleX:r},100).call(function(){d=!1;s_oGame.restartUpdates();h=!0;n.clickListener();return!0},n)}))};this.clickListener=function(){if(!1===d)k.on("click",function(){this.clicked()},n)};this.display=function(){};this.isFolded=function(){return h};this.getType=function(){return l};this.eliminateCard=function(){d=!0;s_oGame.suspendUpdates();
k.alpha=1;createjs.Tween.get(k).to({alpha:0},400).call(function(){t.removeChild(k);d=!1;s_oGame.restartUpdates()})};this._init(a,b,c,e,f)}
var CLevels=function(){var a=CARD_HEIGHT/2+.2*CANVAS_HEIGHT,b=CANVAS_WIDTH/2,c=(CANVAS_HEIGHT-a)/2+a,e=CANVAS_HEIGHT-a;return function(f){var d=s_aCardsPerLevel[f-1];d>MAX_CARDS&&(d=MAX_CARDS);f={cardZoomFactor:1,cardsNum:d,cardsPos:[],timeAllotted:1E3*s_aSecsPerLevel[f-1]};for(var h=1;.1<=h;h-=.01)for(var l=2;6>=l;l+=1){var g=d/l;if(g*(CARD_WIDTH*h+30*h)<=CANVAS_WIDTH&&l*(CARD_HEIGHT*h+30*h)<=e&&0===d%l){for(var d=b-(g-1)*(CARD_WIDTH*h+30*h)*.5,q=c-(a+.5*((CARD_HEIGHT*h+30*h)*(l-1)+a)),r=0;r<l;r++)for(var k=
0;k<g;k++)f.cardsPos[r*g+k]=[d+(CARD_WIDTH*h+30*h)*k,q+a+(CARD_HEIGHT*h+30*h)*r];f.cardZoomFactor=h;return f}}}}();
function CNextLevel(){var a,b,c,e,f,d,h;this._init=function(){h=new createjs.Container;h.alpha=0;h.visible=!1;s_oStage.addChild(h);var l=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));a=new createjs.Text(TEXT_LEVELCOMPLETED,"48px "+FONT_GAME,"#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2-80;a.textBaseline="alphabetic";a.textAlign="center";a.shadow=new createjs.Shadow("#000000",3,3,2);b=new createjs.Text(TEXT_MATCH_SCORE,"30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-20;b.textAlign=
"center";b.textBaseline="alphabetic";b.shadow=new createjs.Shadow("#000000",2,2,2);c=new createjs.Text(TEXT_TIMEBONUS,"30px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+14;c.textAlign="center";c.textBaseline="alphabetic";c.shadow=new createjs.Shadow("#000000",2,2,2);f=new createjs.Text(TEXT_LEVEL_SCORE,"34px "+FONT_GAME,"#fff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2+50;f.textAlign="center";f.textBaseline="alphabetic";f.shadow=new createjs.Shadow("#000000",2,2,2);e=new createjs.Text(TEXT_TOTALSCORE,
"48px "+FONT_GAME,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+120;e.textAlign="center";e.textBaseline="alphabetic";e.shadow=new createjs.Shadow("#000000",2,2,2);h.addChild(l,a,b,c,f,e);d=new CTextButton(CANVAS_WIDTH/2,770,s_oSpriteLibrary.getSprite("but_menu_bg"),"CONTINUE",FONT_GAME,"White","24",h);d.addEventListener(ON_MOUSE_UP,this.hide,this)};this.display=function(a,d,q,r,k){b.text=TEXT_MATCH_SCORE+" = "+a;c.text=TEXT_TIMEBONUS+" = "+d;f.text=TEXT_LEVEL_SCORE+" = "+q;e.text=TEXT_TOTALSCORE+
" "+r;h.visible=!0;createjs.Tween.get(h).to({alpha:1},250)};this.hide=function(){h.alpha=0;h.visible=!1;s_oGame.nextLevel()};this.unload=function(){d.unload();s_oStage.removeChild(h)};this._init()}
function CInterface(a){var b,c,e,f,d,h,l,g,q,r,k,n,t,p,v,m,u,w=null,y=null;this._init=function(a){e=30;f=75;p=TEXT_TIMELEFT+a;k=new createjs.Text(p,"36px "+FONT_GAME,"#fff");k.x=e;k.y=f;k.textBaseline="alphabetic";k.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(k);d=CANVAS_WIDTH/2;h=75;_szScore=TEXT_SCORE+0;n=new createjs.Text(_szScore,"36px "+FONT_GAME,"#fff");n.x=d;n.y=h;n.textAlign="center";n.textBaseline="alphabetic";n.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(n);
m=new createjs.Text("X2","150px "+FONT_GAME,"#fff");m.textAlign="center";m.textBaseline="alphabetic";m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;m.shadow=new createjs.Shadow("#000000",2,2,2);m.scaleX=m.scaleY=.1;m.visible=!1;s_oStage.addChild(m);a=s_oSpriteLibrary.getSprite("but_exit");q=CANVAS_WIDTH-a.width/2-20;r=a.height/2+20;var x=s_oSpriteLibrary.getSprite("audio_icon");l=CANVAS_WIDTH-x.width/2*2-10;g=x.height/2+20;v=new CGfxButton(q,r,a,s_oStage);v.addEventListener(ON_MOUSE_UP,this._onExit,this);
!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(t=new CToggle(l,g,x,s_bAudioActive,s_oStage),t.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),b=l-a.width-20,c=g):(b=q-a.width-20,c=r);a=window.document;x=a.documentElement;w=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;y=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(w=!1);w&&!1===inIframe()&&(a=s_oSpriteLibrary.getSprite("but_fullscreen"),
u=new CToggle(b,c,a,s_bFullscreen,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(a,d){n.y=h+d;k.x=e+a;k.y=f+d;v.setPosition(q-a,d+r);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||t.setPosition(l-a,d+g);w&&!1===inIframe()&&u.setPosition(b-a,c+d)};this.unload=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||t.unload();w&&!1===inIframe()&&u.unload();v.unload();s_oStage.removeChild(k);s_oStage.removeChild(n);
s_oInterface=null};this.refreshScore=function(a){n.text=TEXT_SCORE+a};this.showMultiplier=function(a){m.text="X"+a;m.visible=!0;createjs.Tween.get(m).to({scaleX:1,scaleY:1},300,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(m).to({scaleX:.1,scaleY:.1},300,createjs.Ease.cubicIn).call(function(){m.visible=!1})})};this.update=function(a){k.text=TEXT_TIMELEFT+a};this._onExit=function(){s_oGame.unload(!0)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
this._onFullscreenRelease=function(){s_bFullscreen?(y.call(window.document),s_bFullscreen=!1):(w.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CGameOver(){var a,b,c,e,f,d;this._init=function(){e=new createjs.Container;e.alpha=0;e.visible=!1;s_oStage.addChild(e);f=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d=f.on("click",function(){});a=new createjs.Text(TEXT_GAMEOVER,"50px "+FONT_GAME,"#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2-80;a.textBaseline="alphabetic";a.textAlign="center";a.shadow=new createjs.Shadow("#000000",3,3,2);b=new createjs.Text(TEXT_TOTALSCORE+" 0","48px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/
2+50;b.textAlign="center";b.textBaseline="alphabetic";b.shadow=new createjs.Shadow("#000000",2,2,2);e.addChild(f,a,b);c=new CTextButton(CANVAS_WIDTH/2,670,s_oSpriteLibrary.getSprite("but_menu_bg"),TEXT_PLAY_AGAIN,FONT_GAME,"White","24",e);c.addEventListener(ON_MOUSE_UP,this.unload,this)};this.display=function(a){b.text=TEXT_TOTALSCORE+" "+a;e.visible=!0;createjs.Tween.get(e).to({alpha:1},250).call(function(){$(s_oMain).trigger("show_interlevel_ad")});$(s_oMain).trigger("save_score",a)};this.unload=
function(){f.on("click",d);c.unload();s_oStage.removeChild(e);s_oGame.unload(!1)};this._init()}
function CVictory(){var a,b,c,e;this._init=function(){e=new createjs.Container;e.alpha=0;e.visible=!1;s_oStage.addChild(e);var f=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));b=new createjs.Text(TEXT_VICTORY,"38px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-80;b.textBaseline="alphabetic";b.textAlign="center";b.shadow=new createjs.Shadow("#000000",3,3,2);c=new createjs.Text(TEXT_TOTALSCORE,"48px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2+2;c.y=CANVAS_HEIGHT/2;c.textAlign="center";
c.textBaseline="alphabetic";c.shadow=new createjs.Shadow("#000000",2,2,2);e.addChild(f,b,c);a=new CTextButton(CANVAS_WIDTH/2,670,s_oSpriteLibrary.getSprite("but_menu_bg"),TEXT_PLAY_AGAIN,FONT_GAME,"White","24",e);a.addEventListener(ON_MOUSE_DOWN,this.unload,this)};this.display=function(a){c.text=TEXT_TOTALSCORE+"\n"+a;e.visible=!0;createjs.Tween.get(e).to({alpha:1},250).call(function(){$(s_oMain).trigger("show_interlevel_ad")});$(s_oMain).trigger("save_score",a)};this.unload=function(){a.unload();
s_oStage.removeChild(e);s_oGame.unload(!1)};this._init()}
function CCredits(){var a,b,c,e,f;this._init=function(){a=new createjs.Container;s_oStage.addChild(a);var d=s_oSpriteLibrary.getSprite("msg_box");e=createBitmap(d);f=e.on("mousedown",this._onLogoButRelease);e.regX=d.width/2;e.regY=d.height/2;a.addChild(e);a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;d=new createjs.Text(TEXT_DEVELOPED," 30px "+FONT_GAME,"#ffffff");d.y=-80;d.textAlign="center";d.textBaseline="middle";d.lineWidth=300;a.addChild(d);d=new createjs.Text("www.codethislab.com"," 34px "+FONT_GAME,
"#ffffff");d.y=70;d.textAlign="center";d.textBaseline="middle";d.lineWidth=300;a.addChild(d);d=s_oSpriteLibrary.getSprite("logo_ctl");c=createBitmap(d);c.regX=d.width/2;c.regY=d.height/2;a.addChild(c);d=s_oSpriteLibrary.getSprite("but_exit");b=new CGfxButton(240,-120,d,a);b.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){b.setClickable(!1);s_oStage.removeChild(a);b.unload();e.on("mousedown",f)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};
this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()};
